### ISSUE TITLE
Add isEndState boolean to save trajectories

### ISSUE THREAD

**Issue by panlybero** [gtatiya/gym-novel-gridworlds#1]
Could we add an indicator as to whether the state is a an end state to the recording wrapper? It would help with organizing the collected data into trajectories for methods that look at series of states. An alternative is to add an integer indicating a global counter for the trajectories to each state.

**Comment by gtatiya** [comment]
I added `last_done` in `state_trajectories`. It's a boolean that is False for non-terminal states and True for Terminate state. Does this solves your issue?

**Comment by panlybero** [comment]
Yes it does. Thanks!
