### ISSUE TITLE
training NovelGridworld-v0 is not working

### ISSUE THREAD

**Issue by jaydeep-work** [gtatiya/gym-novel-gridworlds#2]
(gridenv) root@office2-B85M-D2V-SI:/home/office2/Jd_desk/RL_shortest_path/gym-novel-gridworlds/tests# python train.py
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    env = LidarInFront(env)
  File "/home/office2/Jd_desk/RL_shortest_path/gym-novel-gridworlds/gym_novel_gridworlds/observation_wrappers.py", line 21, in __init__
    items_to_exclude = ['air', self.goal_item_to_craft]
  File "/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/gym/core.py", line 223, in __getattr__
    return getattr(self.env, name)
  File "/home/office2/Jd_desk/RL_shortest_path/gym_grid_1/gridenv/lib/python3.7/site-packages/gym/core.py", line 223, in __getattr__
    return getattr(self.env, name)
AttributeError: 'NovelGridworldV0Env' object has no attribute 'goal_item_to_craft'

**Comment by gtatiya** [comment]
You got the above error because you used `LidarInFront` wrapper for NovelGridworld-v0. Wrappers are not supported by NovelGridworld-v0 to NovelGridworld-v5. I will add this information in the README. If you comment out `LimitActions` and `LidarInFront` wrappers in the current train.py, you should be able to train NovelGridworld-v0. Thanks!

**Comment by gtatiya** [comment]
I have added a note about it here: https://github.com/gtatiya/gym-novel-gridworlds#deprecated-environments.
